name: Branch Checks
description: Action to check code consistency

runs:
  using: composite
  steps:
    - name: Check Formatting
      shell: bash
      run: pnpm format:check

    - name: Lint Code
      shell: bash
      run: pnpm lint

    - name: Type Check
      shell: bash
      run: pnpm typecheck

    - name: Package Lint
      shell: bash
      run: pnpm lint:package

    - name: Test Coverage
      shell: bash
      continue-on-error: true
      run: pnpm test:coverage

    - name: Upload Coverage Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          **/coverage/
          packages/*/coverage/
        retention-days: 30

    - name: Coverage Report
      uses: davelosert/vitest-coverage-report-action@v2
      if: github.event_name == 'pull_request'
      with:
        working-directory: packages/ui
        vite-config-path: vitest.config.ts
        github-token: ${{ inputs.github-token }}

    # Add additional branch checks here.
    # i.e. Tests, Translations, security, and any other additional check
