name: Setup
description: Action to setup PNPM, Node, and install dependencies

runs:
  using: composite
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v6

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version-file: .nvmrc

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v6
      with:
        path: |
          ${{ env.STORE_PATH }}
          node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
